name = "fishermn"
compatibility_date = "2025-12-08"

# Deploy from root for GitHub integration
# The .cfignore file controls what gets excluded
pages_build_output_dir = "./"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "fishermn-db"
database_id = "b851bcff-3f89-4598-8699-00f6920c3077"
